In [1]:
import pandas as pd 
import numpy as np
heart_disease = pd.read_csv(r"C:\Users\HPPro\Documents\GitHub\Codewars\ML\Dataset\heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [2]:
# Create X (feature matrix)
X = heart_disease.drop("target",axis=1)
X

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [3]:
y = heart_disease["target"]
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [24]:
# Choose the right model and hyperparameter 

from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=10)

print(clf.get_params()) # Check paramenter 

# Fit the model to the traning data 
from sklearn.model_selection import train_test_split

X_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.2)
clf.fit(X_train, y_train)

# Make a prediction 
y_preds = clf.predict(x_test)
y_preds

{'bootstrap': True, 'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': None, 'max_features': 'sqrt', 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'monotonic_cst': None, 'n_estimators': 10, 'n_jobs': None, 'oob_score': False, 'random_state': None, 'verbose': 0, 'warm_start': False}


array([1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0], dtype=int64)

In [25]:
y_test

77     1
232    0
160    1
88     1
265    0
      ..
264    0
49     1
203    0
193    0
255    0
Name: target, Length: 61, dtype: int64

In [26]:
x_test

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
77    59    1   1       140   221    0        1      164      1      0.0   
232   55    1   0       160   289    0        0      145      1      0.8   
160   56    1   1       120   240    0        1      169      0      0.0   
88    54    0   2       110   214    0        1      158      0      1.6   
265   66    1   0       112   212    0        0      132      1      0.1   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
264   54    1   0       110   206    0        0      108      1      0.0   
49    53    0   0       138   234    0        0      160      0      0.0   
203   68    1   2       180   274    1        0      150      1      1.6   
193   60    1   0       145   282    0        0      142      1      2.8   
255   45    1   0       142   309    0        0      147      1      0.0   

     slope  ca  thal  
77       2   0     2  
232      1   1     3  
160      0   0     2  
88       1   0     2  
265      2   1     2  
..     ...  ..   ...  
264      1   1     2  
49       2   0     2  
203      1   0     3  
193      1   2     3  
255      1   3     3  

[61 rows x 13 columns]

In [27]:
# Evaluate the model 
clf.score(X_train , y_train)

0.9958677685950413

In [28]:
clf.score(x_test,y_test)

0.8524590163934426

In [29]:
from sklearn.metrics import classification_report, confusion_matrix , accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.79      0.88      0.83        25
           1       0.91      0.83      0.87        36

    accuracy                           0.85        61
   macro avg       0.85      0.86      0.85        61
weighted avg       0.86      0.85      0.85        61



In [32]:
confusion_matrix(y_test,y_preds)

array([[22,  3],
       [ 6, 30]], dtype=int64)

In [31]:
accuracy_score(y_test,y_preds)

0.8524590163934426

In [21]:
# Improve the model 
# Try different amout of n_estimators 
np.random.seed(75)
for i in range(10,110,10):
    print(f"Trying model with {i} estimators...")
    clf=RandomForestClassifier(n_estimators=i)
    clf.fit(X_train,y_train)
    im_preds = clf.predict(x_test)
    print(f"Model accuracy on test set : {clf.score(x_test,y_test) * 100:.2f}%")
    print(classification_report(y_test,im_preds))
    print(confusion_matrix(y_test,im_preds))

Trying model with 10 estimators...
Model accuracy on test set : 86.89%
              precision    recall  f1-score   support

           0       0.88      0.88      0.88        32
           1       0.86      0.86      0.86        29

    accuracy                           0.87        61
   macro avg       0.87      0.87      0.87        61
weighted avg       0.87      0.87      0.87        61

[[28  4]
 [ 4 25]]
Trying model with 20 estimators...
Model accuracy on test set : 78.69%
              precision    recall  f1-score   support

           0       0.83      0.75      0.79        32
           1       0.75      0.83      0.79        29

    accuracy                           0.79        61
   macro avg       0.79      0.79      0.79        61
weighted avg       0.79      0.79      0.79        61

[[24  8]
 [ 5 24]]
Trying model with 30 estimators...
Model accuracy on test set : 77.05%
              precision    recall  f1-score   support

           0       0.76      0.81      0

In [33]:
# Save the model 
import pickle
pickle.dump(clf,open("random_forest_model.pkl","wb"))

In [47]:
loaded_model = pickle.load(open("random_forest_model.pkl","rb"))
print(loaded_model.predict(np.array([55,1,0,160,289,0,0,145,1,0.8,1,1,3]).reshape(1,-1)))

[0]


c:\Users\HPPro\anaconda3\envs\tf\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
