In [26]:
import numpy as np
import pandas as pd 

In [69]:
def info_np(n) -> str:
    print(n)
    return  f"Dim : {n.ndim} , Shape : {n.shape} , Type(Element/Obj) : {n.dtype , type(n)} , a element in array : {n.size}"

In [18]:
d1 = np.array([1,2,3])
d1 , d1.shape


(array([1, 2, 3]), (3,))

In [19]:
d2 = np.array([[1,2,3],
               [4,5,6]])
d2 , d2.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [31]:
d3 = np.array( [[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
                [[10,11,12],
                 [13,14,15],
                 [16,17,18]]] )
d3 , d3.shape

(numpy.ndarray, (2, 3, 3))

In [25]:
print("What is the diemension of np array? : ",d1.ndim , d2.ndim , d3.ndim)
print("What is the type of np array? :",d1.dtype , d2.dtype , d3.dtype)
print("How many element? : ",d1.size , d2.size , d3.size)

What is the diemension of np array? :  1 2 3
What is the type of np array? : int32 int32 int32
How many element? :  3 6 18


In [29]:
# Create a Dataframe from a Numpy array 
df = pd.DataFrame(d2 , columns=["A" , "B" , "C"])
df

A  B  C
0  1  2  3
1  4  5  6

In [102]:
# press "shift + TAB" To see the comment 
ones : np.ndarray = np.ones((3) , np.int32)
info_np(ones)

[1 1 1]


"Dim : 1 , Shape : (3,) , Type(Element/Obj) : (dtype('int32'), <class 'numpy.ndarray'>) , a element in array : 3"

In [47]:
zeros : np.ndarray = np.zeros((2,3) , dtype=np.float32)
info_np(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


'Dim : 2 , Shape : (2, 3) , Type : float32 , a element in array : 6'

In [57]:
range_array : np.ndarray = np.arange(1,11,1)
info_np(range_array)

[ 1  2  3  4  5  6  7  8  9 10]


"Dim : 1 , Shape : (10,) , Type(Element/Obj) : (dtype('int32'), <class 'numpy.ndarray'>) , a element in array : 10"

In [72]:
np.random.seed(seed=23)
random_array : np.ndarray = np.random.randint(low=0 , high=10 ,dtype=int , size=(3,5))
info_np(random_array)

[[3 6 8 9 6]
 [8 7 9 3 6]
 [1 2 5 5 0]]


"Dim : 2 , Shape : (3, 5) , Type(Element/Obj) : (dtype('int32'), <class 'numpy.ndarray'>) , a element in array : 15"

In [73]:
# Viewing array and matrices 

np.unique(random_array)

array([0, 1, 2, 3, 5, 6, 7, 8, 9])

In [74]:
d3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [97]:
d3[:2 , :1 , :3]

array([[[ 1,  2,  3]],

       [[10, 11, 12]]])

In [103]:
## Manipulation & comparing arrays
# Arimetric
d1 + ones

array([2, 3, 4])

In [104]:
d1 - ones

array([0, 1, 2])

In [105]:
d1 * ones

array([1, 2, 3])

In [106]:
d1 * d2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [109]:
d1 / ones

array([1., 2., 3.])

In [110]:
d2 // d1

array([[1, 1, 1],
       [4, 2, 2]])

In [120]:
d3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [121]:
d3n = d3.reshape((3,2,3))
d3n

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [125]:
d3n*d2

array([[[  1,   4,   9],
        [ 16,  25,  36]],

       [[  7,  16,  27],
        [ 40,  55,  72]],

       [[ 13,  28,  45],
        [ 64,  85, 108]]])

In [130]:
d3z = (d2*d3n).reshape( (2,3,3))
d3z

array([[[  1,   4,   9],
        [ 16,  25,  36],
        [  7,  16,  27]],

       [[ 40,  55,  72],
        [ 13,  28,  45],
        [ 64,  85, 108]]])

In [135]:
rarray = np.random.random(100000)
rarray[:10]

array([0.16736546, 0.781931  , 0.72358649, 0.70766707, 0.02180529,
       0.22725523, 0.06348778, 0.20036691, 0.10306151, 0.13309033])

In [137]:
'''
Use Python's method ( sum() ) on Python datatype and use Nunmpy's methods on Numpy array ( np.sum() ).
'''
%timeit sum(rarray)
%timeit np.sum(rarray)

9.11 ms ± 266 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
46.8 µs ± 2.18 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [138]:
np.max(rarray)

0.9999963093402477

In [139]:
np.min(rarray)

3.0390162726323666e-06

In [140]:
np.std(rarray)

0.2893508617785095

In [141]:
np.mean(rarray)

0.5010833360332054

In [142]:
np.median(rarray)

0.5013716993126707

In [143]:
np.var(rarray)

0.08372392121196612